ALTER TABLE customers ADD COLUMN deleted BOOLEAN DEFAULT  FALSE;
ALTER TABLE customers ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE loan_applications ADD COLUMN deleted BOOLEAN DEFAULT  FALSE;
ALTER TABLE loan_applications ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

